### ISSUE TITLE
 fs_cli error when connecting to FreeSWITCH using drachtio/drachtio-freeswitch-mrf Docker image on Debian 11 host

### ISSUE THREAD

**Issue by akey1982** [drachtio/docker-drachtio-freeswitch-mrf#13]
Description:

I'm experiencing an issue with fs_cli when trying to connect to FreeSWITCH using the drachtio/drachtio-freeswitch-mrf:latest Docker image on a Debian 11 host. When I run fs_cli, I receive the following error message:

**fs_cli.c:1691 main() Error Connecting []**

Running ps aux | grep freeswitch | grep -v grep shows that FreeSWITCH seems to be running:

**root 1 1.8 3.1 1662152 122288 ? Ssl 10:19 0:59 freeswitch**

This suggests that FreeSWITCH is indeed started and running, but fs_cli is unable to establish a connection with it. Any help or suggestions to resolve this issue would be greatly appreciated.

**Comment by davehorton** [comment]
check you are using the correct password as found in /usr/local/freeswitch/config/autoload_configs/event_socket.conf.xml
