### ISSUE TITLE
mrf_sip_profile.xml from Base causes issue

### ISSUE THREAD

**Issue by lylepratt** [drachtio/docker-drachtio-freeswitch-mrf#9]
It seems that the base image copies a file `mrf_sip_profile.xml` which conflicts with the `mrf.xml` SIP Profile that this Docker image tries to use. I'm not sure why `mrf_sip_profile.xml` exists though. Is this intended?

**Comment by lylepratt** [comment]
This is where the base image creates the `mrf_sip_profile.xml`:
https://github.com/drachtio/docker-drachtio-freeswitch-base/blob/main/Dockerfile#L95

When I start the `docker-drachtio-freeswitch-mrf` container, I end up with both `mrf.xml` and `mrf_sip_profile.xml` in my `sip_profiles` directory. Freeswitch then complains about the port it tries to bind to already being taken (by the other profile). Perhaps there a flag or something I can use to prevent that file from Base from being created? I can always fork base, but I figure this is a problem.

**Comment by davehorton** [comment]
yes, thanks for this....will look into it

**Comment by lylepratt** [comment]
Strangely I'm also unable to connect to the freeswitch cli using `fs_cli`, although according to `freeswitch.log` it is running.

**Comment by lylepratt** [comment]
Ahh I see the problem with the cli:
It looks like the default event socket password is no longer "Cluecon", but "JambonzR0ck$"

**Comment by davehorton** [comment]
yes, sorry I did change that a while back.  Also, this issue should really be in the base repo....I've checked in a fix there for the original issue, so going to close this here.
